### ISSUE TITLE
Issue wih cmake sources

### ISSUE THREAD

**Issue by Crivella** [anharmonic/d3q#13]
I was trying to compile d3q via the QE cmake, first problem for which i will open an issue on the QE repo is that they are pointing to a very old commit where function definitions were different.

After manually updating the commit to pull the latest one I encountered a second problem:

I had to manually edit the `CMakeLists.txt` file by adding `minpack/` in front of the sources at [lapackified/chkder.c](https://github.com/anharmonic/d3q/blob/8b1f985c2d95b94880f0cdf4a7188243de5f0911/CMakeLists.txt#L126)

Not sure if there is a better way/flag that will already resolve this or if this should be fixed

**Comment by paulatz** [comment]
Thank you Davide, this library is a bit of a pain to compile, however but you do not need it unless you want to use the TDPH code (fitting for constants to molecular dynamics). I'll try to fix it in a permanent way
cheers

**Comment by ye-luo** [comment]
@paulatz it seems that the current issue is only missing files or incorrect path in CMakeLists.txt. Could you fix that?

**Comment by paulatz** [comment]
Thank you Ye Luo, there is problem is deep in the minpack code, which requires some "fortran passing function pointer to c back to fortran" which I have only managed to make it work with intel fortran. Note that it is a good reason to keep cmakelist ou of date, but I have been dragging my feet trying to decide how to ship a code that compiles reliably.
cheers

**Comment by ye-luo** [comment]
> Thank you Ye Luo, there is problem is deep in the minpack code, which requires some "fortran passing function pointer to c back to fortran" which I have only managed to make it work with intel fortran. Note that it is a good reason to keep cmakelist ou of date, but I have been dragging my feet trying to decide how to ship a code that compiles reliably. cheers

Is this a linking issue or failure at run? So far I have no issue compiling with GNU but I assume `d3q/minpack/distributed` is not activated in CMake.

**Comment by paulatz** [comment]
It's only activated if you compile with scalapack support, it used to not compile at all with my version of gfortran. Apart from that, the d3q version which I have uploaded a few minutes ago seems to compile with both make and cmake

**Comment by ye-luo** [comment]
> It's only activated if you compile with scalapack support, it used to not compile at all with my version of gfortran. Apart from that, the d3q version which I have uploaded a few minutes ago seems to compile with both make and cmake

I see. We don't activate scalapack in D3Q when building inside QE. Due to the removal of a function in upstream QE, need a last minute change https://github.com/anharmonic/d3q/pull/16

**Comment by ye-luo** [comment]
Curious, what version of gfortran were you using.

**Comment by paulatz** [comment]
I'm not sure, the one that came with Ubuntu 20.04 I guess, which is 11. There is no need to do last minute changes, as the specific parallel features are only use in a very specific code which not even completely documented yet. 
I'm adding an if() in CmakeList to use the correct library depending on the scalapack activation, but I get some error about plmdif_c0 not being available (both the subroutine and its USE are included in ifdef __SCALAPACK, should be ok)

**Comment by ye-luo** [comment]
> I'm not sure, the one that came with Ubuntu 20.04 I guess, which is 11. There is no need to do last minute changes, as the specific parallel features are only use in a very specific code which not even completely documented yet. I'm adding an if() in CmakeList to use the correct library depending on the scalapack activation, but I get some error about plmdif_c0 not being available (both the subroutine and its USE are included in ifdef __SCALAPACK, should be ok)

I see the distributed case can be dealt later. I was referring to the removal of `remove_stack_limit` calls in  #16 as the last minute change.

**Comment by paulatz** [comment]
Ok, no problem than. As long as SCALAPACK is not used it should be fine, and I have removed TDPH from default compilation, which should prevent these errors
